# Generated by Django 5.2.3 on 2025-06-29 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_receta_receta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chef',
        ),
        migrations.DeleteModel(
            name='Moderador',
        ),
    ]
