# Generated by Django 5.2.3 on 2025-06-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_categoria_receta_categoria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Categorias',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='categoria',
        ),
        migrations.AddField(
            model_name='receta',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='portfolio.categorias'),
        ),
    ]
