# Generated by Django 5.2.3 on 2025-07-12 00:27

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_receta_autor_receta_fecha_alter_receta_receta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='receta',
            name='receta',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
