# Generated by Django 5.2.3 on 2025-07-12 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_categorias_nombre_alter_receta_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscriptor',
            name='apellido',
        ),
    ]
