# Generated by Django 5.2.3 on 2025-07-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='categorias',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(blank=True, default='portfolio/img/default-avatar.jpg', null=True, upload_to='avatars/'),
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
        migrations.AddField(
            model_name='receta',
            name='categorias',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
